name: Examples
on: push

jobs:
  setup-nodenv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - uses: ./setup-nodenv # this would be nodenv/actions/setup-nodenv@v2 for most users
      - run: nodenv --version

  node-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - id: nodenv
        uses: ./node-version # this would be nodenv/actions/node-version@v2 for most users
      - uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nodenv.outputs.node-version }}"
      - run: node -v
