name: Sync Master
on:
  push:
    branches: main
    workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: zofrex/mirror-branch@v1.0.2
          target-branch: master
          force: false
